/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GalleryImage = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addGalleryImage' : IDL.Func([GalleryImage], [IDL.Nat], []),
  'deleteContact' : IDL.Func([IDL.Nat], [], []),
  'deleteGalleryImage' : IDL.Func([IDL.Nat], [], []),
  'getAllContacts' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
  'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getGalleryImage' : IDL.Func([IDL.Nat], [GalleryImage], ['query']),
  'submitContact' : IDL.Func([ContactForm], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GalleryImage = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addGalleryImage' : IDL.Func([GalleryImage], [IDL.Nat], []),
    'deleteContact' : IDL.Func([IDL.Nat], [], []),
    'deleteGalleryImage' : IDL.Func([IDL.Nat], [], []),
    'getAllContacts' : IDL.Func([], [IDL.Vec(ContactForm)], ['query']),
    'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getGalleryImage' : IDL.Func([IDL.Nat], [GalleryImage], ['query']),
    'submitContact' : IDL.Func([ContactForm], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };